### ISSUE TITLE
Problem with jython-shaded-2.7.0

### ISSUE THREAD

**Issue by gildasmorvan** [scijava/scripting-jython#10]
Dear scripting-jython developers,

I encountered a problem with scijava kernel related to jython-shaded-2.7.0. When executing my code with that version of jython I had the following error when calling the constructor of a superclass (coded in java):
```
TypeError: Default constructor failed for Java superclass
```
Since my code was running well outside jupyter with jython 2.7.1 I replaced  jython-shaded-2.7.0.jar by  jython-shaded-2.7.1.jar that I found [there](http://central.maven.org/maven2/org/scijava/jython-shaded/2.7.1/). And now everything runs normally 😀

So I think it would be a good idea to upgrade  jython-shaded in scripting-jython. 

Best regards,

Gildas

Note 1: my code can be found [there](https://github.com/gildasmorvan/similar2logo/blob/master/similar2logo-examples/src/main/doc/notebooks/Python/Python%20Passive%20turtle%20example.ipynb)

Note 2: I also opened the same issue [there](https://github.com/scijava/scijava-jupyter-kernel/issues/89) thinking it was related to scijava-jupyter-kernel.

**Comment by ctrueden** [comment]
We have not upgraded to 2.7.1 yet due to [this serious performance bug](http://bugs.jython.org/issue2604), as discussed on [this forum thread](http://forum.imagej.net/t/jython-2-7-1-released/5943/3).

Unfortunately, it seems like a fix for the performance issue is very tricky, and probably not forthcoming any time soon. Maybe we should go to 2.7.1 for the bug-fixes, and live with the worse performance in some situations? What do you think?

**Comment by ctrueden** [comment]
I have not played with it much, to be honest. But the bug you describe is serious enough that I'm going to upgrade our software stack, including this component, to use 2.7.1 now. And if there are grievous problems because of it, we can discuss whether to roll back.

Thanks again for the bug report, @gildasmorvan!
